tablist:
  # The top text of the tab menu
  header: '<newline><rainbow>Your Server!</rainbow><newline>'
  # The bottom text of the tab menu
  footer: '<newline><gray>Ping: <white>%player_ping%<newline>'
  # Format for the player's tab display name, works with PAPI
  player-name: '%luckperms_prefix%%player_name%'
scoreboard:
  # Should the scoreboard feature of this plugin be enabled?
  enabled: true
  # Scoreboard name that is displayed for the player
  name: "<rainbow>Your Server!</rainbow>"
  # Scoreboard entries to be displayed for the player
  entries:
    - "<gray>Ping: <white>%player_ping%"
    - "<red>Test"
multi-server:
  # Should we enable multi-server support, this means that every connected server will update tab users between each other. all config options are still independent excluding the player's prefix and suffix
  enabled: false
  # Unique identifier for this node on your mutli-server network
  name: "TabCompleted-Server-1"
  # What channel should we listen on? This MUST be the same for all servers you want to be linked, you can use different channels on the same network but players will be seperated by channels
  channel: "TabCompleted-Channel-1"
  # Ip used to connect to the redis server
  ip: "192.168.0.233"
  # Port used to connect to the redis server
  port: 20050
  # Password used to connect to the redis server
  password: "abc123"
misc:
  # Should player collision be enabled?
  collision: true
  nametag: "%luckperms_prefix%%player_name%%luckperms_suffix%"